version: "3"
services:
  csv-datamart-api:
    image: csv-datamart:v1
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    # Remove port bindings when using host network mode
    # ports:
    #   - 4448:4448
    env_file:
      - .env
    volumes:
      - .:/app
      - ./storage:/app/storage:rw
    network_mode: host